version: "3"

services:
  influxdb:
    build: influxdb
    volumes:
      - ./db-data:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "2003:2003"
  grafana:
    build: grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb