version: "3"

services:
  influxdb:
    build: influxdb
    ports:
      - "8086:8086"
      - "2003:2003"
  grafana:
    image: grafana/grafana:4.4.1
    environment: 
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    ports:
      - "3000:3000"
    depends_on:
      - influxdb